networks:
  laravel-vue:

volumes:
  mysql_data:

services:
  app:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "8001:80"
    volumes:
      - ./backend:/var/www/html:delegated
    depends_on:
      - php
      - redis
      - mysql
      - mailhog
    networks:
      - laravel-vue

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: codeacademy_laravel_vue
      MYSQL_PASSWORD: root
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-vue

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    ports:
      - "8002:80"
    networks:
      - laravel-vue

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "9001:9000"
    volumes:
      - ./backend:/var/www/html:delegated
    networks:
      - laravel-vue

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - laravel-vue

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8003:8025"
    networks:
      - laravel-vue

  vue-ui:
    build:
      context: ./frontend
    ports:
      - "8085:5173"
    stdin_open: true
    volumes:
      - './frontend:/app'
    networks:
      - laravel-vue
    entrypoint: [ "sh", "-c" ]
    command: [ "npm install && npm run dev" ]
